### ISSUE TITLE
Status of Project / Issue Tracker

### ISSUE THREAD

**Issue by mattLummus** [RoelGo/CamSucks#1]
Hey Roel,

Firstly, thanks for contributing this to Open Source.
I'm working on a PC build right now (parts still coming in) and I went with a Kraken x61. I am aware of the issues with Cam regardless of it being good hardware and want an alternative software solution. 
In addition, many other companies and products are binding their hardware products to proprietary software, which I think is a bad solution and kind of a bigger issue for a couple reasons: lack of transparency (quality of application, rootware, etc), overhead (don't want stuff I don't need to run the underlying hardware) and complexity by running different proprietary systems from different companies - CAM vs Link for instance. Theoretically, I should be able to run hardware under one low-overhead manager of my choosing. I paid for the hardware, I shouldn't be bound to their software.

So I want to help this project because I think its a big need for it right now.
What is the status of the project? What are the glaring issues? 

Let me know if there is anything I can maybe help with!

**Comment by RoelGo** [comment]
Hi 

I haven't done any work at all on this project. I actually pressed the fork button by accident and I just rolled with it. I would really like to work on it though. 

However I did already make an alternative for CAM in Java. You can find the project on my profile I think. I intend to translate my design from that project to this one. 

If you would like to contribute you might wanna start with looking through my documentation in that project. 

The biggest challenge is probably gonna be figuring out the communication with the hardware. The GRID+ uses serial communication over a USB COM. Maybe the kraken does the same? 

I won't be able to contribute with the development for a while I think but I will be able to help with brainstorming. 

Thank you a lot for your interest and I'm sorry if I disappoint.

**Comment by RoelGo** [comment]
Ok first of all I'm stupid. I thought you replied to my other project.  The fork of open hardware monitor.  I'm a complete noob when it comes to github.

So yeah my advice still holds true about the communication with the kraken, that's gonna be the hard part. 

The biggest issue of this project is probably that we are using Java since it's not really intended to be used this close to the hardware. So the biggest next step would be to merge this project with open hardware monitor like I intend to do in the future.

**Comment by mattLummus** [comment]
Yeah, its a nice reference though. Ideally abstracting different serial coms from different components would be great - that's really the bad part about everything being proprietary, you end up also being tied to GUI's and forced add on's and such. 

I'm not tied to any language at least in figuring this out. Porting as not difficult once you figure out the architecture. I'll probably try to map as rizvanp did initally.

**Comment by RoelGo** [comment]
Ok sounds great. Keep me posted. As I said before I would like to help with brainstorming.

**Comment by akej74** [comment]
Hi, @mattLummus, please have a look at [this subreddit](https://www.reddit.com/r/NZXT/comments/552v29/grid_control_a_free_alternative_to_cam/), there is a high demand from the NZXT users for a CAM replacement :-) [This project](https://github.com/jaksi/leviathan) also looks very interesting, the Kraken X61 protocol has been reverse-engineered.
